"""
Tool definitions and registry for multi-agent system.
Each tool is a LangChain Tool that agents can invoke.
"""
from __future__ import annotations

from typing import Optional

from langchain_core.tools import tool

from src.utils.config import get_settings
from src.utils.logging import get_logger

logger = get_logger(__name__)


@tool
def web_search(query: str) -> str:
    """Search the web for current information on a topic.

    Args:
        query: The search query string
    """
    try:
        from duckduckgo_search import DDGS
        settings = get_settings()
        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=settings.max_search_results))
        if not results:
            return f"No results found for: {query}"
        formatted = []
        for r in results:
            formatted.append(f"Title: {r['title']}\nURL: {r['href']}\nSnippet: {r['body']}\n")
        return "\n---\n".join(formatted)
    except Exception as e:
        logger.error("web_search_failed", query=query, error=str(e))
        return f"Search failed: {str(e)}"


@tool
def arxiv_search(query: str, max_results: int = 5) -> str:
    """Search ArXiv for academic papers on a topic.

    Args:
        query: The research topic to search for
        max_results: Maximum number of papers to return
    """
    try:
        import arxiv
        search = arxiv.Search(
            query=query,
            max_results=max_results,
            sort_by=arxiv.SortCriterion.Relevance,
        )
        results = []
        for paper in search.results():
            results.append(
                f"Title: {paper.title}\n"
                f"Authors: {', '.join(a.name for a in paper.authors[:3])}\n"
                f"Published: {paper.published.strftime('%Y-%m-%d')}\n"
                f"Abstract: {paper.summary[:500]}\n"
                f"URL: {paper.entry_id}"
            )
        return "\n\n---\n\n".join(results) if results else f"No papers found for: {query}"
    except Exception as e:
        logger.error("arxiv_search_failed", query=query, error=str(e))
        return f"ArXiv search failed: {str(e)}"


@tool
def wikipedia_search(query: str) -> str:
    """Search Wikipedia for background information on a topic.

    Args:
        query: The topic to look up on Wikipedia
    """
    try:
        import wikipedia
        results = wikipedia.search(query, results=3)
        if not results:
            return f"No Wikipedia articles found for: {query}"
        page = wikipedia.page(results[0], auto_suggest=False)
        return f"Title: {page.title}\nURL: {page.url}\nSummary: {page.summary[:1000]}"
    except Exception as e:
        return f"Wikipedia search failed: {str(e)}"


@tool
def calculator(expression: str) -> str:
    """Evaluate a mathematical expression safely.

    Args:
        expression: Mathematical expression to evaluate (e.g., '2 + 2 * 3')
    """
    try:
        import ast
        tree = ast.parse(expression, mode="eval")
        # Only allow safe math operations
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                return "Error: Function calls not allowed in calculator"
        result = eval(compile(tree, "<calc>", "eval"))
        return f"Result: {result}"
    except Exception as e:
        return f"Calculation error: {str(e)}"


@tool
def code_executor(code: str) -> str:
    """Execute Python code for data analysis in a sandboxed environment.

    Args:
        code: Python code to execute (data analysis, statistics, etc.)
    """
    import io
    import contextlib

    stdout_capture = io.StringIO()
    try:
        safe_globals = {"__builtins__": {}}
        safe_imports = {
            "math": __import__("math"),
            "statistics": __import__("statistics"),
            "json": __import__("json"),
            "collections": __import__("collections"),
        }
        safe_globals.update(safe_imports)

        with contextlib.redirect_stdout(stdout_capture):
            exec(code, safe_globals)

        output = stdout_capture.getvalue()
        return output if output else "Code executed successfully (no output)"
    except Exception as e:
        return f"Execution error: {str(e)}"


@tool
def markdown_formatter(content: str, title: str = "Research Report") -> str:
    """Format content into a well-structured Markdown document.

    Args:
        content: Raw content to format
        title: Title for the document
    """
    formatted = f"# {title}\n\n"
    formatted += f"*Generated by Multi-Agent Research Assistant*\n\n"
    formatted += "---\n\n"
    formatted += content
    return formatted


@tool
def memory_lookup(query: str) -> str:
    """Search the shared agent memory for previously gathered information.

    Args:
        query: Topic or keyword to search in memory
    """
    try:
        from src.memory.shared_memory import SharedMemory
        memory = SharedMemory()
        results = memory.search(query, top_k=3)
        if not results:
            return "No relevant information found in memory."
        return "\n\n---\n\n".join(
            f"[Memory] {r['content'][:500]}" for r in results
        )
    except Exception as e:
        return f"Memory lookup failed: {str(e)}"


# ── Tool Registry ──────────────────────────────────────────

TOOL_REGISTRY = {
    "web_search": web_search,
    "arxiv_search": arxiv_search,
    "wikipedia_search": wikipedia_search,
    "calculator": calculator,
    "code_executor": code_executor,
    "markdown_formatter": markdown_formatter,
    "memory_lookup": memory_lookup,
}


def get_tools_for_agent(tool_names: list[str]) -> list:
    """Resolve tool names to actual tool instances."""
    tools = []
    for name in tool_names:
        if name in TOOL_REGISTRY:
            tools.append(TOOL_REGISTRY[name])
        else:
            logger.warning("tool_not_found", tool=name)
    return tools
